name: Javadoc Quality Check

on: [push, pull_request]

jobs:
  check-javadoc:
    runs-on: ubuntu-latest

    env:
      ANYJ_THRESHOLD: 0.90
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package

      - name: Run Javadoc Metric Checker
        run: |
          java -jar target/pat-prototype-1.0-SNAPSHOT.jar -p src/test -anyj $ANYJ_THRESHOLD
        continue-on-error: false
        
      - name: Notify Success
        if: success()
        run: echo "Javadoc-Check bestanden!"
